import "./globals.css";
import SportovaNavbar from "@/components/SportovaNavbar";
import Footer from "@/components/Footer";
import NewsletterSection from "@/components/NewsletterSection";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ProductProvider } from '@/components/ProductContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ProductProvider>
          <div>
            <SportovaNavbar />
          </div>
          {children}
          <NewsletterSection />
          <Footer />
        </ProductProvider>
      </body>
    </html>
  );
}
