import "./globals.css";
import SportovaNavbar from "@/components/SportovaNavbar";
import Footer from "@/components/Footer";
import NewsletterSection from "@/components/NewsletterSection";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ProductProvider } from '@/components/ProductContext';
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata: Metadata = {
  title: "SPORTOVA for Muhammadali",
  description: "Generated by Me",
};
  
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              window.$crisp=[];
              window.CRISP_WEBSITE_ID="ebb2d2cc-bc27-4ac0-af9e-4ebd3623ae22";
              (function(){
                d=document;
                s=d.createElement("script");
                s.src="https://client.crisp.chat/l.js";
                s.async=1;
                d.getElementsByTagName("head")[0].appendChild(s);
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ProductProvider>
          <AuthProvider>
            <div>
              <SportovaNavbar />
            </div>
            {children}
            <NewsletterSection />
            <Footer />
          </AuthProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
